swagger: "2.0"
info:
  description: This is the swagger file that goes with the server code
  version: "0.0.1"
  title: Swagger REST template
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/"

paths: